web_finngen_r6/lib/risteys_web/router.ex
defmodule RisteysWeb.Router do
  use RisteysWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["csv", "json"]
  end

  scope "/", RisteysWeb do
    pipe_through :browser

    get "/", HomeController, :index
    get "/methods", MethodsController, :index
    get "/changelog", ChangelogController, :index
    get "/phenocode/:name", PhenocodeController, :show
  end

  scope "/api", RisteysWeb do
    pipe_through :api

    get "/phenocode/:name/assocs.json", PhenocodeController, :get_assocs_json
    get "/phenocode/:name/assocs.csv", PhenocodeController, :get_assocs_csv
    get "/phenocode/:name/drugs.json", PhenocodeController, :get_drugs_json
    get "/phenocode/:name/drugs.csv", PhenocodeController, :get_drugs_csv
  end
end

web_finngen_r6/lib/risteys_web/templates/home/index.html.eex
<section class="card my-16">
	<h3>Search all endpoints in Risteys</h3>
	<div id="app-search-results">
	</div>
</section>

<article class="demophenos">
	<article class="card item-a">
		<h4>Miscellaneous main endpoints</h4>
		<ul>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "J10_ASTHMA") %>">Asthma</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "H7_GLAUCOMA") %>">Glaucoma</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "H7_AMD") %>">Age-related macular degeneration (whether dry or wet)</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "HYPOTHY_LEVOTHY") %>">Hypothyroidism, levothyroxin purchases</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "HYPOTHYROIDISM") %>">Hypothyroidism (congenital or acquired)</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "M13_ANKYLOSPON") %>">Ankylosing spondylitis</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "O15_PRE_OR_ECLAMPSIA") %>">Pre-eclampsia or eclampsia</a></li>
		</ul>
	</article>

	<article class="card item-b">
		<h4>Diseases of the skin and subcutaneous tissue</h4>
		<ul>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "L12_ATOPIC") %>">Atopic dermatitis</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "ATOPIC_STRICT") %>">Atopic  dermatitis, strict definition</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "ATOPIC_STRICT_REIMB") %>">Atopic dermatitis, strict definition with reimbursement</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "L12_PSORIASIS") %>">Psoriasis</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "PSORI_STRICT") %>">Psoriasis (vulgaris), strict definition</a></li>
		</ul>
	</article>

	<article class="card item-c">
		<h4>Endocrine, nutritional and metabolic diseases</h4>
		<ul>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "HYPOTHY_REIMB") %>">Hypothyroidism, drug reimbursement</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "HYPOTHY_PURCHASE") %>">Hypothyroidism and >3 levothyroxin purchases</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "E4_PCOS") %>">Polycystic ovarian syndrome</a></li>
		</ul>
	</article>

	<article class="card item-d mb-8">
		<h4>Rheuma endpoints</h4>
		<ul>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "RHEUMA_SEROPOS_OTH") %>">Other/unspecified seropositive rheumatoid arthritis</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "GOUT_STRICT") %>">Gout, strict definition</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "GOUT") %>">Gout, FINNGEN</a></li>
		</ul>
	</article>

	<article class="card item-e">
		<h4>Diseases of the circulatory system</h4>
		<ul>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "I9_AF") %>">Atrial fibrillation and flutter</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "I9_AF_REIMB") %>">Atrial fibrillation and flutter with reimbursement</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "I9_ISCHHEART") %>">Ischemic heart diseases</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "I9_MI") %>">Myocardial infarction</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "I9_MI_STRICT") %>">Myocardial infarction, strict</a></li>
		</ul>
	</article>

	<article class="card item-f">
		<h4>Diabetes endpoints</h4>
		<ul>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "T1D_STRICT") %>">Type 1 diabetes, strict definition</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "T1D_STRICT1") %>">Type 1 diabetes, strict definition, subgroup&nbsp;1</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "T1D_STRICT2") %>">Type 1 diabetes, strict definition, subgroup&nbsp;2</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "T2D") %>">Type 2 diabetes, definitions combined</a></li>
		</ul>
	</article>

	<article class="card item-g">
		<h4>Neoplasms</h4>
		<ul>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "C3_BREAST") %>">Malignant neoplasm of breast</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "C3_BRONCHUS_LUNG") %>">Malignant neoplasm of bronchus and lung</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "C3_COLON") %>">Malignant neoplasm of colon</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "C3_PROSTATE") %>">Malignant neoplasm of prostate</a></li>
		</ul>
	</article>

	<article class="card item-h">
		<h4>Diseases of the nervous system</h4>
		<ul>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "G6_AD_WIDE") %>">Alzheimer’s disease, wide definition</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "G6_MS") %>">MS-disease / Multiple Sclerosis</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "G6_PARKINSON") %>">Parkinson's disease</a></li>
		</ul>
	</article>

	<article class="card item-i">
		<h4>Diseases of the digestive system</h4>
		<ul>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "APPENDICITIS_BROAD") %>">Appendicitis, broad definition</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "K11_APPENDACUT") %>">Acute appendicitis</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "APPENDACUT_COMPLIC") %>">Acute appendicitis, with complications</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "APPENDACUT_NOCOMPLIC") %>">Acute appendicitis, no complications</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "GAST_OPER") %>">Any gastric operation</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "K11_IBD_STRICT") %>">Inflammatory bowel disease, strict (require KELA)</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "K11_CD_STRICT") %>">Crohn disease (strict definition, require KELA)</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "K11_CD_STRICT2") %>">Crohn disease (strict definition, require KELA, min 2 HDR)</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "CHOLELITH_BROAD") %>">Cholelithiasis, broad definition with cholecystitis</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "K11_HERNIA") %>">Hernia</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "ABDOM_HERNIA") %>">Hernia of abodminal wall</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "ABDOM_HERNIA_POSTOP") %>">Hernia of abodminal wall, postoperative</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "FEMHER_BILATERAL") %>">Femoral hernia, bilateral</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "FEMHER_UNILATERAL") %>">Femoral hernia, unilateral</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "HERING_BILATERAL") %>">Inguinal hernia, bilateral</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "HERING_UNILATERAL") %>">Inguinal hernia, unilateral</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "FEMINGHER_BILATERAL") %>">Inguinal or femoral hernia, bilateral</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "FEMNINGHER_UNILATERAL") %>">Inguinal of femoral hernia, unilateral</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "K11_UC_STRICT") %>">Ulcerative colitis (strict definition, require KELA)</a></li>
			<li><a href="<%= Routes.phenocode_path(@conn, :show, "K11_UC_STRICT2") %>">Ulcerative colitis (strict definition, require KELA, min 2 HDR)</a></li>
		</ul>
	</article>
</article>

<script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>