web_finngen_r6/lib/risteys_web/router.ex
defmodule RisteysWeb.Router do
  use RisteysWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["csv", "json"]
  end

  scope "/", RisteysWeb do
    pipe_through :browser

    get "/", HomeController, :index
    get "/methods", MethodsController, :index
    get "/changelog", ChangelogController, :index
    get "/phenocode/:name", PhenocodeController, :show
  end

  scope "/api", RisteysWeb do
    pipe_through :api

    get "/phenocode/:name/assocs.json", PhenocodeController, :get_assocs_json
    get "/phenocode/:name/assocs.csv", PhenocodeController, :get_assocs_csv
    get "/phenocode/:name/drugs.json", PhenocodeController, :get_drugs_json
    get "/phenocode/:name/drugs.csv", PhenocodeController, :get_drugs_csv
  end
end

web_finngen_r6/lib/risteys_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Risteys FinnGen R6 - <%= @page_title %></title>
	<link rel="apple-touch-icon" href="<%= Routes.static_path(@conn, "/images/apple-touch-icon.png") %>">
	<link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/images/favicon-32x32.png") %>">
	<link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/images/favicon-16x16.png") %>">
	<link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
</head>
<body class="font-sans bg-grey-light">

	<header class="bg-blue-darker text-white">
		<div class="fluid-container">
			<div class="header py-2">
				<h1 class="text-4xl" id="link-home">
					<span id="toggle-nav-menu" class="navmenu">≡</span>
					<a href="<%= Routes.static_path(@conn, "/") %>">Risteys <span class="font-normal" style="font-size: 0.75em">R6</span></a>
				</h1>
				<nav id="nav-narrow">
					<p class="grid-1col">
						<a href="/methods">Methods</a>
						<a href="/changelog">Changelog</a>
						<a href="https://github.com/dsgelab/risteys/" target="_blank" rel="noopener noreferrer external">GitHub</a>
						<a href="https://airtable.com/shrTzTwby7JhFEqi6" target="_blank" rel="noopener noreferrer external"><b>Contact &amp; Feedback</b></a>
					</p>
					<p class="grid-1col">
						<span class="section-title">On this page:</span>
						<a href="#endpoint-definition">Endpoint definition</a>
						<a href="#summary-statistics">Summary statistics</a>
						<a href="#correlations">Correlations</a>
						<a href="#survival-analyses">Survival analyses</a>
						<a href="#drugs-statistics">Drug statistics</a>
					</p>
				</nav>
				<div class="searchbox">
					<div id="pheno-searchbox"></div>
				</div>
				<div class="actions text-lg">
					<a href="/methods">Methods</a>
					<a href="/changelog">Changelog</a>
					<a href="https://github.com/dsgelab/risteys/" target="_blank" rel="noopener noreferrer external">GitHub</a>
					<a href="https://airtable.com/shrTzTwby7JhFEqi6" target="_blank" rel="noopener noreferrer external"><b>Contact &amp; Feedback</b></a>
				</div>
			</div>
		</div>
	</header>
	<div class="h-2 bg-blue-dark shadow-lg"></div>

<div class="bgcream py-8">
	<%# allow the footer to look like it fills to the bottom of the page %>
	<%= render @view_module, @view_template, assigns %>
</div>
	<footer class="bg-grey-light text-lg border-t border-grey py-8 leading-normal">
		<div class="fluid-container">
			<p>Risteys <a href="<%= Routes.changelog_path(@conn, :index) %>#v1.11.0">v1.11.0</a> (2021-01-18).</p>
			<p>
				<a href="https://airtable.com/shrTzTwby7JhFEqi6" target="_blank" rel="noopener noreferrer external" >Contact us</a> for feedback or <a href="https://github.com/dsgelab/risteys/issues/new" target="_blank" rel="noopener noreferrer external">open an issue</a> on Risteys GitHub.
			</p>
			<p>Made at <a href="https://www.fimm.fi/" target="_blank" rel="noopener noreferrer external">FIMM</a> in Helsinki, Finland.</p>
		</div>
	</footer>

	<script src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>

web_finngen_r6/lib/risteys_web/templates/layout/minimal.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Risteys FinnGen R6</title>
	<link rel="apple-touch-icon" href="<%= Routes.static_path(@conn, "/images/apple-touch-icon.png") %>">
	<link rel="icon" type="image/png" sizes="32x32" href="<%= Routes.static_path(@conn, "/images/favicon-32x32.png") %>">
	<link rel="icon" type="image/png" sizes="16x16" href="<%= Routes.static_path(@conn, "/images/favicon-16x16.png") %>">
	<link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
</head>

<body class="bgcream">
	<header class="bg-blue-darker text-white">
		<div class="fluid-container">
			<div class="header frontpage py-2">
				<div class="actions text-lg">
					<a href="/methods">Methods</a>
					<a href="/changelog">Changelog</a>
					<a href="https://github.com/dsgelab/risteys/" target="_blank" rel="noopener noreferrer external">GitHub</a>
					<a href="https://airtable.com/shrTzTwby7JhFEqi6" target="_blank" rel="noopener noreferrer external"><b>Contact &amp; Feedback</b></a>
				</div>
				<h1 class="text-5xl" id="link-home">
					<span id="toggle-nav-menu" class="navmenu">≡</span>
					<a href="<%= Routes.static_path(@conn, "/") %>">Risteys <span class="font-normal text-4xl">R6</span></a>
				</h1>
				<h2>Explore FinnGen data at the phenotype level</h2>
				<nav id="nav-narrow">
					<p class="grid-1col">
						<a href="/methods">Methods</a>
						<a href="/changelog">Changelog</a>
						<a href="https://github.com/dsgelab/risteys/" target="_blank" rel="noopener noreferrer external">GitHub</a>
						<a href="https://airtable.com/shrTzTwby7JhFEqi6" target="_blank" rel="noopener noreferrer external"><b>Contact &amp; Feedback</b></a>
					</p>
				</nav>
			</div>
		</div>
	</header>
	<div class="h-2 bg-blue-dark shadow-lg mb-8"></div>







<div class="fluid-container">
  <%= render @view_module, @view_template, assigns %>
</div>
</body>
</html>